timescale.sv
$EHGU_HOME/ehgu/ehgu_config_pkg.sv
$EHGU_HOME/ehgu/ehgu_basic_pkg.sv
$EHGU_HOME/ehgu/ehgu_clkdiv_fractional.sv
$EHGU_HOME/ehgu/ehgu_cntr.sv
$EHGU_HOME/ehgu/ehgu_dly.sv
$EHGU_HOME/ehgu/ehgu_edges.sv
$EHGU_HOME/ehgu/ehgu_fedge.sv
$EHGU_HOME/ehgu/ehgu_redge.sv
$EHGU_HOME/ehgu/ehgu_rst_sync.sv

$EHGU_HOME/thee/thee_mathsci_consts_pkg.sv
$EHGU_HOME/thee/thee_utils_pkg.sv
$EHGU_HOME/thee/thee_clk_gen_module.sv
$EHGU_HOME/thee/thee_clk_freq_meter.sv
$EHGU_HOME/thee/thee_pfd.sv
$EHGU_HOME/thee/thee_integrator.sv
$EHGU_HOME/thee/thee_charge_pump.sv
$EHGU_HOME/thee/thee_vco.sv
$EHGU_HOME/thee/thee_low_pass_filter.sv
rom_comb.sv
rom_comb_file_read.sv
tb.sv
