timescale.sv
$EHGU_HOME/ehgu/ehgu_config_pkg.sv
$EHGU_HOME/ehgu/ehgu_basic_pkg.sv
$EHGU_HOME/ehgu/ehgu_ram_dual_port.sv
$EHGU_HOME/ehgu/ehgu_sr_mem.sv
$EHGU_HOME/thee/thee_mathsci_consts_pkg.sv
$EHGU_HOME/thee/thee_utils_pkg.sv
$EHGU_HOME/thee/thee_clk_gen_module.sv
trace_back.v
lcs_alnmat.v
lcs_subseq.v
lcs_seq0.v
lcs_seq1.v
lcs_trace.v
lcs.v
tb.sv
