timescale.sv
../../ehgu/ehgu_config_pkg.sv
../../ehgu/ehgu_basic_pkg.sv
../../ehgu/ehgu_clkdiv_fractional.sv
../../ehgu/ehgu_cntr.sv
../../ehgu/ehgu_dly.sv
../../ehgu/ehgu_edges.sv
../../ehgu/ehgu_fedge.sv
../../ehgu/ehgu_redge.sv
../../ehgu/ehgu_rst_sync.sv

../../thee/thee_mathsci_consts_pkg.sv
../../thee/thee_utils_pkg.sv
../../thee/thee_clk_gen_module.sv
../../thee/thee_integrator.sv
ds_adc_ana.sv
ds_adc_dig.sv
ds_adc.sv
tb.sv
