timescale.sv
$EHGU_HOME/ehgu/ehgu_config_pkg.sv
$EHGU_HOME/ehgu/ehgu_basic_pkg.sv
$EHGU_HOME/ehgu/ehgu_ram_dual_port.sv
$EHGU_HOME/ehgu/ehgu_sr_mem.sv
$EHGU_HOME/thee/thee_mathsci_consts_pkg.sv
$EHGU_HOME/thee/thee_utils_pkg.sv
$EHGU_HOME/thee/thee_clk_gen_module.sv
moving_average.v
tb.sv
