timescale.sv
../../ehgu/ehgu_config_pkg.sv
../../ehgu/ehgu_basic_pkg.sv
../../ehgu/ehgu_ram_dual_port.sv
../../ehgu/ehgu_sr_mem.sv
../../thee/thee_mathsci_consts_pkg.sv
../../thee/thee_utils_pkg.sv
../../thee/thee_clk_gen_module.sv
moving_average.v
tb.sv
