timescale.sv
MYPADOUT.sv
pads.sv
$EHGU_HOME/ehgu/ehgu_delay_line.sv
$EHGU_HOME/ehgu/ehgu_ring_osc.sv
$EHGU_HOME/ehgu/ehgu_config_pkg.sv
$EHGU_HOME/ehgu/ehgu_basic_pkg.sv
$EHGU_HOME/ehgu/ehgu_clkdiv.sv
core.sv
osc_die_top.sv
vt0.sv
tb.sv
